server:
  port: 8091
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
#spring.jpa.hibernate.ddl-auto=none

  h2:
    console:
      enabled: true
#spring.h2.console.path=/h2-console
      settings:
        trace: false
        web-allow-others: false

  cloud:
    config:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
